//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace covid {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("covid.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a afghanistan.
        /// </summary>
        internal static string afghanistan {
            get {
                return ResourceManager.GetString("afghanistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a albania.
        /// </summary>
        internal static string albania {
            get {
                return ResourceManager.GetString("albania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a algeria.
        /// </summary>
        internal static string algeria {
            get {
                return ResourceManager.GetString("algeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a andorra.
        /// </summary>
        internal static string andorra {
            get {
                return ResourceManager.GetString("andorra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a angola.
        /// </summary>
        internal static string angola {
            get {
                return ResourceManager.GetString("angola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a antigua-and-barbuda.
        /// </summary>
        internal static string antigua_and_barbuda {
            get {
                return ResourceManager.GetString("antigua-and-barbuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a argentina.
        /// </summary>
        internal static string argentina {
            get {
                return ResourceManager.GetString("argentina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a armenia.
        /// </summary>
        internal static string armenia {
            get {
                return ResourceManager.GetString("armenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a australia.
        /// </summary>
        internal static string australia {
            get {
                return ResourceManager.GetString("australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a austria.
        /// </summary>
        internal static string austria {
            get {
                return ResourceManager.GetString("austria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a azerbaijan.
        /// </summary>
        internal static string azerbaijan {
            get {
                return ResourceManager.GetString("azerbaijan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bahamas.
        /// </summary>
        internal static string bahamas {
            get {
                return ResourceManager.GetString("bahamas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bahrain.
        /// </summary>
        internal static string bahrain {
            get {
                return ResourceManager.GetString("bahrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bangladesh.
        /// </summary>
        internal static string bangladesh {
            get {
                return ResourceManager.GetString("bangladesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a barbados.
        /// </summary>
        internal static string barbados {
            get {
                return ResourceManager.GetString("barbados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a belarus.
        /// </summary>
        internal static string belarus {
            get {
                return ResourceManager.GetString("belarus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a belgium.
        /// </summary>
        internal static string belgium {
            get {
                return ResourceManager.GetString("belgium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a belize.
        /// </summary>
        internal static string belize {
            get {
                return ResourceManager.GetString("belize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a benin.
        /// </summary>
        internal static string benin {
            get {
                return ResourceManager.GetString("benin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bhutan.
        /// </summary>
        internal static string bhutan {
            get {
                return ResourceManager.GetString("bhutan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bolivia.
        /// </summary>
        internal static string bolivia {
            get {
                return ResourceManager.GetString("bolivia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bosnia-and-herzegovina.
        /// </summary>
        internal static string bosnia_and_herzegovina {
            get {
                return ResourceManager.GetString("bosnia-and-herzegovina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a botswana.
        /// </summary>
        internal static string botswana {
            get {
                return ResourceManager.GetString("botswana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a brazil.
        /// </summary>
        internal static string brazil {
            get {
                return ResourceManager.GetString("brazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a brunei.
        /// </summary>
        internal static string brunei {
            get {
                return ResourceManager.GetString("brunei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bulgaria.
        /// </summary>
        internal static string bulgaria {
            get {
                return ResourceManager.GetString("bulgaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a burkina-faso.
        /// </summary>
        internal static string burkina_faso {
            get {
                return ResourceManager.GetString("burkina-faso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a burundi.
        /// </summary>
        internal static string burundi {
            get {
                return ResourceManager.GetString("burundi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cambodia.
        /// </summary>
        internal static string cambodia {
            get {
                return ResourceManager.GetString("cambodia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cameroon.
        /// </summary>
        internal static string cameroon {
            get {
                return ResourceManager.GetString("cameroon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a canada.
        /// </summary>
        internal static string canada {
            get {
                return ResourceManager.GetString("canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cape-verde.
        /// </summary>
        internal static string cape_verde {
            get {
                return ResourceManager.GetString("cape-verde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a central-african-republic.
        /// </summary>
        internal static string central_african_republic {
            get {
                return ResourceManager.GetString("central-african-republic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a chad.
        /// </summary>
        internal static string chad {
            get {
                return ResourceManager.GetString("chad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a chile.
        /// </summary>
        internal static string chile {
            get {
                return ResourceManager.GetString("chile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a china.
        /// </summary>
        internal static string china {
            get {
                return ResourceManager.GetString("china", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a colombia.
        /// </summary>
        internal static string colombia {
            get {
                return ResourceManager.GetString("colombia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a comoros.
        /// </summary>
        internal static string comoros {
            get {
                return ResourceManager.GetString("comoros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a congo-brazzaville.
        /// </summary>
        internal static string congo_brazzaville {
            get {
                return ResourceManager.GetString("congo-brazzaville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a congo-kinshasa.
        /// </summary>
        internal static string congo_kinshasa {
            get {
                return ResourceManager.GetString("congo-kinshasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a costa-rica.
        /// </summary>
        internal static string costa_rica {
            get {
                return ResourceManager.GetString("costa-rica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cote-divoire.
        /// </summary>
        internal static string cote_divoire {
            get {
                return ResourceManager.GetString("cote-divoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a croatia.
        /// </summary>
        internal static string croatia {
            get {
                return ResourceManager.GetString("croatia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cuba.
        /// </summary>
        internal static string cuba {
            get {
                return ResourceManager.GetString("cuba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cyprus.
        /// </summary>
        internal static string cyprus {
            get {
                return ResourceManager.GetString("cyprus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a czech-republic.
        /// </summary>
        internal static string czech_republic {
            get {
                return ResourceManager.GetString("czech-republic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a denmark.
        /// </summary>
        internal static string denmark {
            get {
                return ResourceManager.GetString("denmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a djibouti.
        /// </summary>
        internal static string djibouti {
            get {
                return ResourceManager.GetString("djibouti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dominica.
        /// </summary>
        internal static string dominica {
            get {
                return ResourceManager.GetString("dominica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dominican-republic.
        /// </summary>
        internal static string dominican_republic {
            get {
                return ResourceManager.GetString("dominican-republic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ecuador.
        /// </summary>
        internal static string ecuador {
            get {
                return ResourceManager.GetString("ecuador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a egypt.
        /// </summary>
        internal static string egypt {
            get {
                return ResourceManager.GetString("egypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a el-salvador.
        /// </summary>
        internal static string el_salvador {
            get {
                return ResourceManager.GetString("el-salvador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a equatorial-guinea.
        /// </summary>
        internal static string equatorial_guinea {
            get {
                return ResourceManager.GetString("equatorial-guinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a eritrea.
        /// </summary>
        internal static string eritrea {
            get {
                return ResourceManager.GetString("eritrea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a estonia.
        /// </summary>
        internal static string estonia {
            get {
                return ResourceManager.GetString("estonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ethiopia.
        /// </summary>
        internal static string ethiopia {
            get {
                return ResourceManager.GetString("ethiopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fiji.
        /// </summary>
        internal static string fiji {
            get {
                return ResourceManager.GetString("fiji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a finland.
        /// </summary>
        internal static string finland {
            get {
                return ResourceManager.GetString("finland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a france.
        /// </summary>
        internal static string france {
            get {
                return ResourceManager.GetString("france", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a gabon.
        /// </summary>
        internal static string gabon {
            get {
                return ResourceManager.GetString("gabon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a gambia.
        /// </summary>
        internal static string gambia {
            get {
                return ResourceManager.GetString("gambia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a georgia.
        /// </summary>
        internal static string georgia {
            get {
                return ResourceManager.GetString("georgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a germany.
        /// </summary>
        internal static string germany {
            get {
                return ResourceManager.GetString("germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ghana.
        /// </summary>
        internal static string ghana {
            get {
                return ResourceManager.GetString("ghana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a greece.
        /// </summary>
        internal static string greece {
            get {
                return ResourceManager.GetString("greece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a grenada.
        /// </summary>
        internal static string grenada {
            get {
                return ResourceManager.GetString("grenada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a guatemala.
        /// </summary>
        internal static string guatemala {
            get {
                return ResourceManager.GetString("guatemala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a guinea.
        /// </summary>
        internal static string guinea {
            get {
                return ResourceManager.GetString("guinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a guinea-bissau.
        /// </summary>
        internal static string guinea_bissau {
            get {
                return ResourceManager.GetString("guinea-bissau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a guyana.
        /// </summary>
        internal static string guyana {
            get {
                return ResourceManager.GetString("guyana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a haiti.
        /// </summary>
        internal static string haiti {
            get {
                return ResourceManager.GetString("haiti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a holy-see-vatican-city-state.
        /// </summary>
        internal static string holy_see_vatican_city_state {
            get {
                return ResourceManager.GetString("holy-see-vatican-city-state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a honduras.
        /// </summary>
        internal static string honduras {
            get {
                return ResourceManager.GetString("honduras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hungary.
        /// </summary>
        internal static string hungary {
            get {
                return ResourceManager.GetString("hungary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a iceland.
        /// </summary>
        internal static string iceland {
            get {
                return ResourceManager.GetString("iceland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a india.
        /// </summary>
        internal static string india {
            get {
                return ResourceManager.GetString("india", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a indonesia.
        /// </summary>
        internal static string indonesia {
            get {
                return ResourceManager.GetString("indonesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a iran.
        /// </summary>
        internal static string iran {
            get {
                return ResourceManager.GetString("iran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a iraq.
        /// </summary>
        internal static string iraq {
            get {
                return ResourceManager.GetString("iraq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ireland.
        /// </summary>
        internal static string ireland {
            get {
                return ResourceManager.GetString("ireland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a israel.
        /// </summary>
        internal static string israel {
            get {
                return ResourceManager.GetString("israel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a italy.
        /// </summary>
        internal static string italy {
            get {
                return ResourceManager.GetString("italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a jamaica.
        /// </summary>
        internal static string jamaica {
            get {
                return ResourceManager.GetString("jamaica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a japan.
        /// </summary>
        internal static string japan {
            get {
                return ResourceManager.GetString("japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a jordan.
        /// </summary>
        internal static string jordan {
            get {
                return ResourceManager.GetString("jordan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kazakhstan.
        /// </summary>
        internal static string kazakhstan {
            get {
                return ResourceManager.GetString("kazakhstan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kenya.
        /// </summary>
        internal static string kenya {
            get {
                return ResourceManager.GetString("kenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a korea-south.
        /// </summary>
        internal static string korea_south {
            get {
                return ResourceManager.GetString("korea-south", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kosovo.
        /// </summary>
        internal static string kosovo {
            get {
                return ResourceManager.GetString("kosovo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kuwait.
        /// </summary>
        internal static string kuwait {
            get {
                return ResourceManager.GetString("kuwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kyrgyzstan.
        /// </summary>
        internal static string kyrgyzstan {
            get {
                return ResourceManager.GetString("kyrgyzstan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lao-pdr.
        /// </summary>
        internal static string lao_pdr {
            get {
                return ResourceManager.GetString("lao-pdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a latvia.
        /// </summary>
        internal static string latvia {
            get {
                return ResourceManager.GetString("latvia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lebanon.
        /// </summary>
        internal static string lebanon {
            get {
                return ResourceManager.GetString("lebanon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lesotho.
        /// </summary>
        internal static string lesotho {
            get {
                return ResourceManager.GetString("lesotho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a liberia.
        /// </summary>
        internal static string liberia {
            get {
                return ResourceManager.GetString("liberia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a libya.
        /// </summary>
        internal static string libya {
            get {
                return ResourceManager.GetString("libya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a liechtenstein.
        /// </summary>
        internal static string liechtenstein {
            get {
                return ResourceManager.GetString("liechtenstein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lithuania.
        /// </summary>
        internal static string lithuania {
            get {
                return ResourceManager.GetString("lithuania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a luxembourg.
        /// </summary>
        internal static string luxembourg {
            get {
                return ResourceManager.GetString("luxembourg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a macedonia.
        /// </summary>
        internal static string macedonia {
            get {
                return ResourceManager.GetString("macedonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a madagascar.
        /// </summary>
        internal static string madagascar {
            get {
                return ResourceManager.GetString("madagascar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a malawi.
        /// </summary>
        internal static string malawi {
            get {
                return ResourceManager.GetString("malawi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a malaysia.
        /// </summary>
        internal static string malaysia {
            get {
                return ResourceManager.GetString("malaysia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a maldives.
        /// </summary>
        internal static string maldives {
            get {
                return ResourceManager.GetString("maldives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mali.
        /// </summary>
        internal static string mali {
            get {
                return ResourceManager.GetString("mali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a malta.
        /// </summary>
        internal static string malta {
            get {
                return ResourceManager.GetString("malta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mauritania.
        /// </summary>
        internal static string mauritania {
            get {
                return ResourceManager.GetString("mauritania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mauritius.
        /// </summary>
        internal static string mauritius {
            get {
                return ResourceManager.GetString("mauritius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mexico.
        /// </summary>
        internal static string mexico {
            get {
                return ResourceManager.GetString("mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a moldova.
        /// </summary>
        internal static string moldova {
            get {
                return ResourceManager.GetString("moldova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a monaco.
        /// </summary>
        internal static string monaco {
            get {
                return ResourceManager.GetString("monaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mongolia.
        /// </summary>
        internal static string mongolia {
            get {
                return ResourceManager.GetString("mongolia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a montenegro.
        /// </summary>
        internal static string montenegro {
            get {
                return ResourceManager.GetString("montenegro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a morocco.
        /// </summary>
        internal static string morocco {
            get {
                return ResourceManager.GetString("morocco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mozambique.
        /// </summary>
        internal static string mozambique {
            get {
                return ResourceManager.GetString("mozambique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a myanmar.
        /// </summary>
        internal static string myanmar {
            get {
                return ResourceManager.GetString("myanmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a namibia.
        /// </summary>
        internal static string namibia {
            get {
                return ResourceManager.GetString("namibia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nepal.
        /// </summary>
        internal static string nepal {
            get {
                return ResourceManager.GetString("nepal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a netherlands.
        /// </summary>
        internal static string netherlands {
            get {
                return ResourceManager.GetString("netherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a new-zealand.
        /// </summary>
        internal static string new_zealand {
            get {
                return ResourceManager.GetString("new-zealand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nicaragua.
        /// </summary>
        internal static string nicaragua {
            get {
                return ResourceManager.GetString("nicaragua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a niger.
        /// </summary>
        internal static string niger {
            get {
                return ResourceManager.GetString("niger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nigeria.
        /// </summary>
        internal static string nigeria {
            get {
                return ResourceManager.GetString("nigeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a norway.
        /// </summary>
        internal static string norway {
            get {
                return ResourceManager.GetString("norway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a oman.
        /// </summary>
        internal static string oman {
            get {
                return ResourceManager.GetString("oman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pakistan.
        /// </summary>
        internal static string pakistan {
            get {
                return ResourceManager.GetString("pakistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a palestine.
        /// </summary>
        internal static string palestine {
            get {
                return ResourceManager.GetString("palestine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a panama.
        /// </summary>
        internal static string panama {
            get {
                return ResourceManager.GetString("panama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a papua-new-guinea.
        /// </summary>
        internal static string papua_new_guinea {
            get {
                return ResourceManager.GetString("papua-new-guinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a paraguay.
        /// </summary>
        internal static string paraguay {
            get {
                return ResourceManager.GetString("paraguay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a peru.
        /// </summary>
        internal static string peru {
            get {
                return ResourceManager.GetString("peru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a philippines.
        /// </summary>
        internal static string philippines {
            get {
                return ResourceManager.GetString("philippines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a poland.
        /// </summary>
        internal static string poland {
            get {
                return ResourceManager.GetString("poland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a portugal.
        /// </summary>
        internal static string portugal {
            get {
                return ResourceManager.GetString("portugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a qatar.
        /// </summary>
        internal static string qatar {
            get {
                return ResourceManager.GetString("qatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a romania.
        /// </summary>
        internal static string romania {
            get {
                return ResourceManager.GetString("romania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a russia.
        /// </summary>
        internal static string russia {
            get {
                return ResourceManager.GetString("russia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rwanda.
        /// </summary>
        internal static string rwanda {
            get {
                return ResourceManager.GetString("rwanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a saint-kitts-and-nevis.
        /// </summary>
        internal static string saint_kitts_and_nevis {
            get {
                return ResourceManager.GetString("saint-kitts-and-nevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a saint-lucia.
        /// </summary>
        internal static string saint_lucia {
            get {
                return ResourceManager.GetString("saint-lucia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a saint-vincent-and-the-grenadines.
        /// </summary>
        internal static string saint_vincent_and_the_grenadines {
            get {
                return ResourceManager.GetString("saint-vincent-and-the-grenadines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a san-marino.
        /// </summary>
        internal static string san_marino {
            get {
                return ResourceManager.GetString("san-marino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sao-tome-and-principe.
        /// </summary>
        internal static string sao_tome_and_principe {
            get {
                return ResourceManager.GetString("sao-tome-and-principe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a saudi-arabia.
        /// </summary>
        internal static string saudi_arabia {
            get {
                return ResourceManager.GetString("saudi-arabia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a senegal.
        /// </summary>
        internal static string senegal {
            get {
                return ResourceManager.GetString("senegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a serbia.
        /// </summary>
        internal static string serbia {
            get {
                return ResourceManager.GetString("serbia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a seychelles.
        /// </summary>
        internal static string seychelles {
            get {
                return ResourceManager.GetString("seychelles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sierra-leone.
        /// </summary>
        internal static string sierra_leone {
            get {
                return ResourceManager.GetString("sierra-leone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a singapore.
        /// </summary>
        internal static string singapore {
            get {
                return ResourceManager.GetString("singapore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a slovakia.
        /// </summary>
        internal static string slovakia {
            get {
                return ResourceManager.GetString("slovakia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a slovenia.
        /// </summary>
        internal static string slovenia {
            get {
                return ResourceManager.GetString("slovenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a somalia.
        /// </summary>
        internal static string somalia {
            get {
                return ResourceManager.GetString("somalia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a south-africa.
        /// </summary>
        internal static string south_africa {
            get {
                return ResourceManager.GetString("south-africa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a south-sudan.
        /// </summary>
        internal static string south_sudan {
            get {
                return ResourceManager.GetString("south-sudan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spain.
        /// </summary>
        internal static string spain {
            get {
                return ResourceManager.GetString("spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sri-lanka.
        /// </summary>
        internal static string sri_lanka {
            get {
                return ResourceManager.GetString("sri-lanka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sudan.
        /// </summary>
        internal static string sudan {
            get {
                return ResourceManager.GetString("sudan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a suriname.
        /// </summary>
        internal static string suriname {
            get {
                return ResourceManager.GetString("suriname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a swaziland.
        /// </summary>
        internal static string swaziland {
            get {
                return ResourceManager.GetString("swaziland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sweden.
        /// </summary>
        internal static string sweden {
            get {
                return ResourceManager.GetString("sweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a switzerland.
        /// </summary>
        internal static string switzerland {
            get {
                return ResourceManager.GetString("switzerland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a syria.
        /// </summary>
        internal static string syria {
            get {
                return ResourceManager.GetString("syria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a taiwan.
        /// </summary>
        internal static string taiwan {
            get {
                return ResourceManager.GetString("taiwan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tajikistan.
        /// </summary>
        internal static string tajikistan {
            get {
                return ResourceManager.GetString("tajikistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tanzania.
        /// </summary>
        internal static string tanzania {
            get {
                return ResourceManager.GetString("tanzania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a thailand.
        /// </summary>
        internal static string thailand {
            get {
                return ResourceManager.GetString("thailand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a timor-leste.
        /// </summary>
        internal static string timor_leste {
            get {
                return ResourceManager.GetString("timor-leste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a togo.
        /// </summary>
        internal static string togo {
            get {
                return ResourceManager.GetString("togo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a trinidad-and-tobago.
        /// </summary>
        internal static string trinidad_and_tobago {
            get {
                return ResourceManager.GetString("trinidad-and-tobago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tunisia.
        /// </summary>
        internal static string tunisia {
            get {
                return ResourceManager.GetString("tunisia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a turkey.
        /// </summary>
        internal static string turkey {
            get {
                return ResourceManager.GetString("turkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a uganda.
        /// </summary>
        internal static string uganda {
            get {
                return ResourceManager.GetString("uganda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ukraine.
        /// </summary>
        internal static string ukraine {
            get {
                return ResourceManager.GetString("ukraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a united-arab-emirates.
        /// </summary>
        internal static string united_arab_emirates {
            get {
                return ResourceManager.GetString("united-arab-emirates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a united-kingdom.
        /// </summary>
        internal static string united_kingdom {
            get {
                return ResourceManager.GetString("united-kingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a united-states.
        /// </summary>
        internal static string united_states {
            get {
                return ResourceManager.GetString("united-states", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a uruguay.
        /// </summary>
        internal static string uruguay {
            get {
                return ResourceManager.GetString("uruguay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a uzbekistan.
        /// </summary>
        internal static string uzbekistan {
            get {
                return ResourceManager.GetString("uzbekistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a venezuela.
        /// </summary>
        internal static string venezuela {
            get {
                return ResourceManager.GetString("venezuela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a vietnam.
        /// </summary>
        internal static string vietnam {
            get {
                return ResourceManager.GetString("vietnam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a western-sahara.
        /// </summary>
        internal static string western_sahara {
            get {
                return ResourceManager.GetString("western-sahara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a yemen.
        /// </summary>
        internal static string yemen {
            get {
                return ResourceManager.GetString("yemen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a zambia.
        /// </summary>
        internal static string zambia {
            get {
                return ResourceManager.GetString("zambia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a zimbabwe.
        /// </summary>
        internal static string zimbabwe {
            get {
                return ResourceManager.GetString("zimbabwe", resourceCulture);
            }
        }
    }
}
